### PR TITLE
Clean up dependencies

### PR DESCRIPTION
**Pull request by mudge**
Before doing any further maintenance on Baton, let's clean up and upgrade any critical dependencies.

### CODE REVIEW

**Comment by mudge** [comment]
An issue here is that Chef (and its dependencies) has broken compatibility with any Ruby older than 2.2.2. If we continue to depend on it, we have to similarly track Ruby versions.

**Comment by thommay** [comment]
Note that the chef omnibus packages will be moving to ruby 2.3.1 after the release on wednesday.

**Comment by mudge** [comment]
Given the rate of Chef's changes, I wonder if that should force us to remove the dependency sooner, c.f. #17

Alternatively, I wonder if it doesn't really matter as Baton applications should be packaged (e.g. with Omnibus) with their own dependencies frozen anyway.

**Comment by mudge** [comment]
Going to close this as, after some discussion with @thommay, it's not safe for us to depend on Chef at all if we want to retain backward compatibility with older Rubies, etc. Let's remove the Chef dependency in favour of explicit Baton server configuration instead.

**Pull request closed without merging**
